export const GET_RESLIST = "GET_RESLIST";
export const SAVE_TOKEN = "SAVE_TOKEN";
export const CLEAR_TOKEN = "CLEAR_TOKEN";
export const GET_MEMBERINFO = "GET_MEMBERINFO";
export const GET_RESINFO = "GET_RESINFO";
export const GET_ORDER = "GET_ORDER";
export const SAVE_SHOPPINGCART = "SAVE_SHOPPINGCART";
export const MINUS_NUMBER_SHOPPINGCART = "MINUS_NUMBER_SHOPPINGCART";