<template>
  <div class="row mt-5 ml-2 mr-2">
    <b-table-simple striped hover outlined>
      <b-thead>
        <b-tr>
          <b-th>#</b-th>
          <b-th>帳號</b-th>
          <b-th>姓名</b-th>
          <b-th>E-mail</b-th>
          <b-th>生日</b-th>
          <b-th>地址</b-th>
          <b-th>權限</b-th>
          <b-th>封鎖</b-th>
        </b-tr>
      </b-thead>
      <b-tbody>
        <b-tr>
          <b-td>1</b-td>
          <b-td>1111</b-td>
          <b-td>1111</b-td>
          <b-td>1111</b-td>
          <b-td>1111</b-td>
          <b-td>1111</b-td>
          <b-td>1111</b-td>
          <b-td>1111</b-td>
        </b-tr>
        <b-tr>
          <b-td>2</b-td>
          <b-td>1111</b-td>
          <b-td>1111</b-td>
          <b-td>1111</b-td>
          <b-td>1111</b-td>
          <b-td>1111</b-td>
          <b-td>1111</b-td>
          <b-td>1111</b-td>
        </b-tr>
      </b-tbody>
    </b-table-simple>
  </div>
</template>